In [ ]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [ ]:
df = pd.read_csv('smart_infrastructure_risk_dataset.csv')
df[['complaint_frequency','damage_size','previous_accidents','repair_delay_days','risk_score']].head(12)

,complaint_frequency,damage_size,previous_accidents,repair_delay_days,risk_score
0,40,7.17,9,126,73.06
1,30,5.36,8,55,48.87
2,30,9.17,15,162,81.78
3,41,8.16,13,100,79.38
4,11,NaN,0,17,16.40
5,15,6.99,5,92,54.50
6,12,1.99,3,35,19.66
7,25,8.63,14,149,82.14
8,16,4.07,3,66,34.12
9,32,3.63,6,31,42.79
10,11,3.00,3,18,25.93
11,29,7.53,15,155,81.60

Data Preprocessing: check median value of damage_size and fill any NA values

In [ ]:
df.damage_size.median()

4.99

In [ ]:
df.damage_size = df.damage_size.fillna(df.damage_size.median())
df[['complaint_frequency','damage_size','previous_accidents','repair_delay_days','risk_score']].head(12)

,complaint_frequency,damage_size,previous_accidents,repair_delay_days,risk_score
0,40,7.17,9,126,73.06
1,30,5.36,8,55,48.87
2,30,9.17,15,162,81.78
3,41,8.16,13,100,79.38
4,11,4.99,0,17,16.40
5,15,6.99,5,92,54.50
6,12,1.99,3,35,19.66
7,25,8.63,14,149,82.14
8,16,4.07,3,66,34.12
9,32,3.63,6,31,42.79
10,11,3.00,3,18,25.93
11,29,7.53,15,155,81.60

In [ ]:
reg = linear_model.LinearRegression()
reg.fit(df[['complaint_frequency','damage_size','previous_accidents','repair_delay_days']], df.risk_score)

LinearRegression()

In [ ]:
reg.coef_

array([0.46908223, 2.87243867, 1.48807705, 0.13033624])

In [ ]:
reg.intercept_

np.float64(2.6130821231640624)

Find the risk score of a complaint with complaint_frequency = 30,damage_size = 5.0, previous_accidents = 5, repair_delay_days = 90

In [ ]:
reg.predict([[30, 5.0, 5, 90]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([50.21838949])

**Y = m1\*X1 + m2\*X2 + m3\*X3 + m4\*X4 + b (m are coefficients and b is intercept)**

In [ ]:
0.46858304*30 + 2.88423075*5.0 + 1.48421895*5 + 0.13006651*90 + 2.613196529362689

50.21892212936269